### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by philpav** [rempsyc/rempsyc#1]
Hi, 

I am unable to install this package in R 4.1.3 on Windows 10 via `devtools::install_github("rempsyc/rempsyc")`.

`
Downloading GitHub repo rempsyc/rempsyc@HEAD
Installing 3 packages: uuid, sp, maptools
Installiere Pakete nach ‘D:/Daten/Documents/R/win-library/4.1’
(da ‘lib’ nicht spezifiziert)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/uuid_1.1-0.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/uuid_1.1-0.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/uuid_1.1-0.zip': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘uuid’ failed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/sp_1.4-7.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/sp_1.4-7.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/sp_1.4-7.zip': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘sp’ failed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/maptools_1.1-4.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/maptools_1.1-4.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/maptools_1.1-4.zip': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘maptools’ failed
√  checking for file 'C:\Users\PhilippXPS\AppData\Local\Temp\RtmpIHIxzF\remotescde010426459\rempsyc-rempsyc-7eb474d/DESCRIPTION' ... 
-  preparing 'rempsyc': (338ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'rempsyc_0.0.2.8.tar.gz'
   
Installiere Paket nach ‘D:/Daten/Documents/R/win-library/4.1’
(da ‘lib’ nicht spezifiziert)
* installing *source* package 'rempsyc' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Fehler in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  es gibt kein Paket namens 'uuid'
Ruft auf: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Ausführung angehalten
ERROR: lazy loading failed for package 'rempsyc'
* removing 'D:/Daten/Documents/R/win-library/4.1/rempsyc'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/PhilippXPS/AppData/Local/Temp/RtmpIHIxzF/filecde0334d60bf/rempsyc_0.0.2.8.tar.gz’ had non-zero exit status
`

**Comment by Buedenbender** [comment]
Rémi let me know if you can not decipher some of the tracebacks, since it's German I could might be of help solving this

**Comment by rempsyc** [comment]
Yes if you’re able to help with this it would be appreciated as I don’t understand German but also you have some experience with the installation trouble of the GitHub packages. Perhaps it is another accent issue?

Le 22 avr. 2022 à 10:41, Buedenbender ***@***.***> a écrit :

﻿

Rémi let me know if you can not decipher some of the tracebacks, since it's German I could might be of help solving this

**Comment by philpav** [comment]
Thanks for your help!
Apparently, there were issues with the server. Installing the packages individually didn't work eithere becuase of an 404 error. I tried it again now and everything works :)
It was just a hiccup. Sorry for the circumstances!
