### ISSUE TITLE
test requires suggtested package

### ISSUE THREAD

**Issue by JanMarvin** [rempsyc/rempsyc#10]
Hi @rempsyc ,

I prepared an `openxlsx2` update and ran a revdep as required for CRAN submissions. This fails with your package with the following error, it has nothing to do with `openxlsx2` but with how you wrote a test. 

To test the function `nice_violin()` you need the additional suggested package `ggsignif`. If this is not installed, you will get an error. Since it is only suggested, the test fails if it is not installed. May I suggest to skip the test for `nice_violin()` if `ggsignif` is not installed, as follows, or otherwise capture the error

```R
skip_if_not_installed("ggsignif")
```

There is an additional warning regarding some `dplyr` functions.

Best regards,
Marvin

[Edit:] fixed spelling

## The entire output:

```R
==> devtools::test()

ℹ Testing rempsyc
Suggested APA citation: Thériault, R. (2022). rempsyc: Convenience functions for psychology 
(R package version 0.1.1) [Computer software]. https://rempsyc.remi-theriault.com 
✔ | F W S  OK | Context
✖ | 1 1     0 | nice_violin [1.1s]                                                                                                  
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning (test-nice_violin.R:2): (code run outside of `test_that()`)
There was 1 warning in `summarize()`.
ℹ In argument: `V1 = .fun(as.data.frame(cur_data()), var)`.
ℹ In group 1: `dose = 0.5`.
Caused by warning:
! `cur_data()` was deprecated in dplyr 1.1.0.
ℹ Please use `pick()` instead.
Backtrace:
 1. rempsyc::nice_violin(data = ToothGrowth, group = "dose", response = "len")
      at test-nice_violin.R:2:0
 7. dplyr:::summarise.grouped_df(...)
 8. dplyr:::summarise_cols(.data, dplyr_quosures(...), by, "summarise")
 9. dplyr:::signal_warnings(warnings_state, error_call)

Error (test-nice_violin.R:27): (code run outside of `test_that()`)
<rlib_error_package_not_found/rlang_error/error/condition>
Error in `nice_violin(data = ToothGrowth, group = "dose", response = "len", 
    comp1 = "0.5", comp2 = "2")`: The package `ggsignif` is required for this function.
Backtrace:
 1. rempsyc::nice_violin(...)
      at test-nice_violin.R:27:0
 2. rlang::check_installed("ggsignif", reason = "for this function.")
      at rempsyc/R/nice_violin.R:345:8
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 1.1 s

[ FAIL 1 | WARN 1 | SKIP 0 | PASS 0 ]
```

**Comment by rempsyc** [comment]
Good idea, will do, thanks!

**Comment by rempsyc** [comment]
Should be fixed on the dev version now! I just submitted a CRAN version not long ago. I think in this case I need to submit a new version to CRAN anyway else yours won't succeed?

**Comment by JanMarvin** [comment]
Thanks for the prompt reaction! No need to update, my submission is already on CRAN. CRAN test with all packages mentioned in DESCRIPTION. It was just something I saw when testing.

**Comment by rempsyc** [comment]
Oh ok, sounds good then, thanks so much for reporting this <3

**Comment by JanMarvin** [comment]
It's already late in Germany, I'll have a look tomorrow.
Sure thing, with the err dependency hell of R such things are really hard to spot :)
