### ISSUE TITLE
Comments on JOSS submission

### ISSUE THREAD

**Issue by kinleyid** [rempsyc/rempsyc#15]
This is a useful library that is clearly already accelerating many researchers' work and reducing the learning curve for those getting started in R. In my review checklist, there are a few items that I've left unchecked: https://github.com/openjournals/joss-reviews/issues/5466#issuecomment-1555922419

1. 
    > Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

   I'm not sure that the stated dependencies on [CRAN](https://cran.r-project.org/web/packages/rempsyc/index.html) are correct. I tried to run a few functions (`nice_table` and `nice_violin`) and got various errors that were resolved by updating dplyr from 1.0.8 to 1.1.0, whereas the stated dependency is >1.0.4.

2.
    > Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

   It seems that only the `nice_violin` function is tested in tests/testthat/. Would it not be better to test all of the functions?

3.
    > Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

   I was unable to find any explicit guidelines for those looking to contribute---I suppose it's obvious that anyone can open a pull request, but it might be worth explicitly stating this somewhere.

Additionally, I have a few minor comments:

* The suggested workflow for tables, using `flextable::save_as_docx`, seems a little bit more cumbersome than the method suggested [here](https://github.com/davidgohel/flextable/issues/117#issuecomment-487126438). `print(my_table, preview ="docx")` opens the flextable in a temporary Word document from which it can be quickly copied and pasted into a manuscript. Perhaps both methods could be mentioned.
* The interpolation of the Inclusion of Other in the Self (IOS) scale points should be explained a little bit more. Specifically, does overlap mean linear overlap (which would scale linearly with the distance between the two circles' centres), or is it a measure of the actual overlapping area of the two circles (which would be measured like [this](https://mathworld.wolfram.com/Circle-CircleIntersection.html))?

**Comment by rempsyc** [comment]
Dear Isaac,

First, a sincere thank you for this very helpful and constructive review. You will find my answers below:

> I'm not sure that the stated dependencies on [CRAN](https://cran.r-project.org/web/packages/rempsyc/index.html) are correct. I tried to run a few functions (nice_table and nice_violin) and got various errors that were resolved by updating dplyr from 1.0.8 to 1.1.0, whereas the stated dependency is >1.0.4.

Thanks, this has been resolved in #14 (as of development version 0.1.2.1, and CRAN version 0.1.3).

> It seems that only the nice_violin function is tested in tests/testthat/. Would it not be better to test all of the functions?

Thanks, I have now added tests for all functions (version 0.1.3.1).

> I was unable to find any explicit guidelines for those looking to contribute---I suppose it's obvious that anyone can open a pull request, but it might be worth explicitly stating this somewhere.

Thanks, this has now been added (accessible through the README page): https://rempsyc.remi-theriault.com/CONTRIBUTING.html

> The interpolation of the Inclusion of Other in the Self (IOS) scale points should be explained a little bit more. Specifically, does overlap mean linear overlap (which would scale linearly with the distance between the two circles' centres), or is it a measure of the actual overlapping area of the two circles (which would be measured like [this](https://mathworld.wolfram.com/Circle-CircleIntersection.html))?

Thank you, I have now clarified this point. In the function description:

```r
#' @description Interpolating the Inclusion of the Other in
#' the Self Scale (IOS; self-other merging) easily. The user provides
#' the IOS score, from 1 to 7, and the function will provide a
#' percentage of actual area overlap between the two circles
#' (i.e., not linear overlap), so it is possible to say, e.g.,
#' that experimental group 1 had an average overlap of X%
#' with the other person, whereas experimental group 2 had
#' an average overlap of X% with the other person.
#' 
#' @details
#' The circles are generated through the
#' `VennDiagram::draw.pairwise.venn()` function and the desired
#' percentage overlap is passed to its `cross.area` argument
#' ("The size of the intersection between the sets"). The percentage
#' overlap values are interpolated from this reference grid:
#' Score of 1 = 0%, 2 = 10%, 3 = 20%, 4 = 30%, 5 = 55%, 6 = 65%,
#' 7 = 85%.
```

In the vignette and paper, I have also added the keyword "overlap _area_" at a few places to avoid ambiguity. Do you feel like this is enough, or would you add something?

By the way, GREAT work on your jsPych plugin for a continuous IOS. Would you be OK if I added a resource link to your plugin in the documentation `overlap_circle()`? If so, would you prefer that I share your [home page](https://kinleyid.github.io/) or [github project](https://github.com/jspsych/jspsych-contrib/tree/main/packages/plugin-ios) URL?

---

Finally, would you have any comments or suggestions on the following points:

- Content, structure, or organization of the paper
- Names of the functions (based on conventions, etc.)
- Names of the arguments within the functions (based on conventions, etc.)

Thanks again.

**Comment by kinleyid** [comment]
Hi Rémi,

This looks great! I think you've addressed all my comments well. I think that using the word "area" is enough to avoid ambiguity---it's a pretty univocal term. I would be happy for you to mention the jsPsych IOS plugin if you think it would be of interest to your users! Probably the link to the github project would make the most sense.

I have no specific comments on the manuscript's writing or on the function/argument names---I think these are all fine as-is. My only general suggestion would be, for wrapper functions to ggplot, to use argument names that match ggplot's as closely as possible. This way users don't have to learn a second set of conventions if they're already somewhat familiar with ggplot.

Cheers,
Isaac

**Comment by rempsyc** [comment]
Thanks a lot! I like the idea of using `ggplot2` original names as arguments. Some universal arguments do translate directly already, like `alpha`, `method`, and `legend.title`, but perhaps `colours` could be changed to `color`, and `border.size` to `linewidth`.

But I'm a bit torn on this. It was an intentional choice when I started the package to give more sensical names for beginners that *don't* know `ggplot2`. This is also my primary audience, as those familiar with `ggplot2` are more likely to use `ggplot2` directly—I think. But I don't know, maybe even `ggplot2` experts could like the convenience of these plotting functions! Thanks again for your input.

**Comment by rempsyc** [comment]
Closing this @kinleyid but my last comment still stands if you find the time to follow my suggestion :)
