### ISSUE TITLE
standardized slopes in nice_table()

### ISSUE THREAD

**Issue by TDJorgensen** [rempsyc/rempsyc#24]
For review of https://github.com/rempsyc/lavaanExtra package, which integrates `nice_table()`: https://github.com/openjournals/joss-reviews/issues/5701

The standardized slopes in `nice_table()` are represented with the Greek letter \beta, which was the symbol recommended in the APA's (2010) publication manual (6th ed.).  Since 2020, the 7th ed. of the APA-style guidelines (Table 6.5) recommends _b_* to avoid confusing sample estimates with population values (likewise, \beta^* can unambiguously represent a standardized population slope.

**Comment by rempsyc** [comment]
Oh wow, I did not realize this major change, but it's true! It's going to take a while to get used to it, but I have changed it. We have to lead by example! Thank you!
