### ISSUE TITLE
Logistic regression

### ISSUE THREAD

**Issue by TomTrebs** [rempsyc/rempsyc#4]
Hi Rémi,

I discovered your rempsyc extension to the flextable package and am quite impressed. 

Can this package handle logistic regression models?

Kind regards
Tom

**Comment by rempsyc** [comment]
Hi Tom, thanks for opening this issue!

Is this what you might need?

``` r
library(report)
library(rempsyc)
log_model <-  glm(vs ~ mpg + cyl + drat, family = binomial, data = mtcars)
log_model |>
  report() |>
  as.data.frame() |>
  nice_table(highlight = TRUE, report = "lm")
```
![](https://i.imgur.com/lYwBcpX.png)
<sup>Created on 2022-09-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rempsyc** [comment]
Or alternatively:

``` r
library(broom)
library(rempsyc)
log_model <-  glm(vs ~ mpg + cyl + drat, family = binomial, data = mtcars)
log_model |>
  tidy(conf.int = TRUE) |>
  as.data.frame() |>
  nice_table(highlight = TRUE, broom = "lm")
```
![](https://i.imgur.com/6enFPsL.png)
<sup>Created on 2022-09-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rempsyc** [comment]
I am closing this issue for now but don't hesitate to reopen it if I have not answered your question.
